; PHP Configuration for MemeSnip
[PHP]
memory_limit = 128M
upload_max_filesize = 25M
post_max_size = 30M
max_execution_time = 300
max_input_time = 300
max_file_uploads = 20

; Error handling & logging
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
